### ISSUE TITLE
Popper won't hide

### ISSUE THREAD

**Issue by tonysamperi** [MrFrankel/ngx-popper#76] opened 2018-09-14 09:57 UTC
When setting this way
```
<button 
 [popper]="popper"
                   [popperHideOnClickOutside]="true"
                   [popperStyles]="{'max-width': '250px'}"
                   [popperPlacement]="'top'"
                   [popperTrigger]="'none'"> TEST </button>

 <popper-content #popper>
            <p class="sfc-font-12 xmat-margin-bottom-0 xmat-margin-top-0">
                Esistono già delle richieste in sospeso per l'utente selezionato.
                <br />
                Vai allo storico richieste per verificare lo stato.
            </p>
        </popper-content>
```

After calling `popper.show()`, popper won't disappear when clicking outside,
even specifying `popperHideOnClickOutside`

**Comment by tonysamperi** [comment] 2018-09-15 18:04
I created a workaround after posting this issue, but I hadn't the time to share..

**component.ts**

```
@ViewChild(PopperContent) popperContent: PopperContent;

myShowFunction(){
    this.managementDisabledInfo.show();
    this._listener = this._renderer.listen("document", "click", this._hidePopper.bind(this));
}

private _hidePopper($event: MouseEvent): void {
    const popperNative = this.popperContent.elemRef.nativeElement;
    if ($event.srcElement &&
        $event.srcElement === popperNative ||
        popperNative.contains($event.srcElement)) {
            return;
    }
    typeof this._listener === typeof isNaN && this._listener();
    // Turn off the listener, because you'll create another
    // if opening the popover again
    this.popperContent.hide();
}

```

**Comment by MrFrankel** [comment] 2018-09-15 18:49
@tonysamperi Hey, the reason the popperHideOnClickOutside dosnt take effect when calling popperContent.show(), is because it is a property of the popper directive.
I'll look into moving this to be managed by the PopperContent.

For now the workaround will work fine, just make sure you clear the listener on ngOnDestroy.

**Comment by tonysamperi** [comment] 2018-09-16 15:33
Alright! Thanks for the answer!
Yes, I remembered to turn off the listener on ngDestroy.

All the best

Tony

**Comment by Dosant** [comment] 2018-10-07 15:40
Also faced this issue, have a repo to reproduce: https://stackblitz.com/edit/ngx-popper-close-bug

**Closed** 2019-07-15 07:51 UTC
Labels: bug
