### ISSUE TITLE
disableDefaultStyling not working in production mode Angular CLI

### ISSUE THREAD

**Issue by distolma** [MrFrankel/ngx-popper#9] opened 2017-09-04 12:35 UTC
Hi, thanks for you work.

I noticed that `PopperController.baseOptions.disableDefaultStyling = true;` in production mode don't work and add `.ngxp-container` selector to the `div`.

![image](https://user-images.githubusercontent.com/16022556/30026644-80b0f0a0-9186-11e7-804d-2ed023d0063d.png)

**Comment by MrFrankel** [comment] 2017-09-04 12:38
@distolma well, I don't use angular cli, so ill have to see if I can reproduce it.
probably since its a static variable angular build ignores runtime changes to it.

Thanks for brining this up, ill look into it..

**Comment by MrFrankel** [comment] 2017-09-04 14:44
@distolma can you tell me where in your code exactly are you calling `PopperController.baseOptions.disableDefaultStyling = true;`?

it should be as soon as possible, prefereably in the bootstrapping of the app.

**Comment by distolma** [comment] 2017-09-04 14:50
I'm calling this stuff in component constructor. 

![image](https://user-images.githubusercontent.com/16022556/30031315-884b1fc6-9199-11e7-94d5-d63ed014f703.png)

**Comment by MrFrankel** [comment] 2017-09-04 14:56
You do realize that setting the baseOptions will effect all popper instances right?

Anyway I have reproduced it, seems to be related to a recent change of mine, will be fixed by tomorrow.

Thanks:)

**Comment by distolma** [comment] 2017-09-04 14:57
How can i modify only current instance of popper?

**Comment by MrFrankel** [comment] 2017-09-04 18:00
[popperDisableStyle]="true"

**Comment by MrFrankel** [comment] 2017-09-05 08:33
Seems to be working now, setting the baseOptions on the PopperController sets the static base options, which apply on all popper elements,
This should run before the elements view's are rendered so best would be to run it before the application it bootstrapped. fixed in  1.1.0

**Closed by MrFrankel** 2017-09-05 08:33 UTC
